version: 2
updates:
  - package-ecosystem: 'npm'
    versioning-strategy: increase
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: 'fs-extra'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    pull-request-branch-name:
      separator: '-'
    labels:
      - 'github-actions'
      - 'dependencies'
