services:
  localstack:
    container_name: 'localstack'
    image: localstack/localstack:latest
    ports:
      - '4566:4566' # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=secretsmanager,sts
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - 'localstack-data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  localstack-data:
    driver: local
