services:
  localstack:
    container_name: 'localstack'
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - 'localstack-data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  localstack-data:
    driver: local
